---
title: "First Knit"
author: "John Garza"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended San Fernando High School. I also graduated from San Fernando High School. I was creative in the english class. In math class I created many answers for the equations. Both subjects were equally difficult. I was better in math when I was younger. Here I have been avoiding math since I believed I could do better in English.             

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
For this class I am using a laptop. My computer for this class is by Apple. On a scale of 1 to 10 where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) I can rate my self. I would rate my self a 10. And you also need to have have internet access. The internet at my home is highly accessible and the connection is typically strong.      
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I am called the same thing by all people. The name I prefer being called and all people call me is my fist or last name John and Garza.    
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
An achievement that I am trying to get is being somebody in life. I am greatly intrested in achieving the things i want to be. I am also greatly interested in every subject that I have taken in college. To get an A in my education is my greatest interest. A degree or certificate im trying to achieve is obtaining a certificate in registered nursing.       
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
My parents have relatives in other states and in the country Mexico. As ive grown I have gone out the US to visit family in Mexico only. I have never been in the military. If i were to get drafted I would chose to join the Marines.   
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




